from abc import ABC, abstractmethod


class BaseLLMProvider(ABC):
    """Abstract interface for all LLM providers."""

    @abstractmethod
    def chat(
        self,
        context: str,
        history: list[dict[str, str]],
        message: str,
    ) -> str:
        """
        Generates a response from the configured LLM.

        Args:
            context: Formatted string summary of the developer's GitHub profile.
            history: List of previous chat messages in the format:
                [
                    {"role": "user", "content": "..."},
                    {"role": "assistant", "content": "..."},
                ]
            message: The latest user prompt.

        Returns:
            Raw string message generated by the LLM.
        """
